# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(720, 520, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_R_1sum = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_R_1sum.setGeometry(QtCore.QRect(70, 40, 113, 20))
        self.lineEdit_R_1sum.setObjectName("lineEdit_R_1sum")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_U_sr_NN = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_U_sr_NN.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.lineEdit_U_sr_NN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_U_sr_NN.setObjectName("lineEdit_U_sr_NN")
        self.label_1 = QtWidgets.QLabel(self.tab)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.lineEdit_X_1sum = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_X_1sum.setGeometry(QtCore.QRect(70, 70, 113, 20))
        self.lineEdit_X_1sum.setObjectName("lineEdit_X_1sum")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(190, 10, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(190, 40, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(190, 70, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.lineEdit_U_sr_NN_2 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_U_sr_NN_2.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.lineEdit_U_sr_NN_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_U_sr_NN_2.setObjectName("lineEdit_U_sr_NN_2")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(190, 10, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(230, 10, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(230, 40, 101, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(190, 40, 31, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_U_sr_NN_3 = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_U_sr_NN_3.setGeometry(QtCore.QRect(70, 40, 113, 20))
        self.lineEdit_U_sr_NN_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_U_sr_NN_3.setObjectName("lineEdit_U_sr_NN_3")
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(10, 40, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(230, 70, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(70, 70, 111, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_Ip0_3ph = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_Ip0_3ph.setGeometry(QtCore.QRect(80, 10, 113, 20))
        self.lineEdit_Ip0_3ph.setObjectName("lineEdit_Ip0_3ph")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(200, 10, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab_5, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Calculation = QtWidgets.QMenu(self.menubar)
        self.menu_Calculation.setObjectName("menu_Calculation")
        self.menu_Report = QtWidgets.QMenu(self.menubar)
        self.menu_Report.setObjectName("menu_Report")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Calculate = QtWidgets.QAction(MainWindow)
        self.action_Calculate.setObjectName("action_Calculate")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Calculation.addAction(self.action_Calculate)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Calculation.menuAction())
        self.menubar.addAction(self.menu_Report.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_U_sr_NN)
        MainWindow.setTabOrder(self.lineEdit_U_sr_NN, self.lineEdit_R_1sum)
        MainWindow.setTabOrder(self.lineEdit_R_1sum, self.lineEdit_X_1sum)
        MainWindow.setTabOrder(self.lineEdit_X_1sum, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "R1S ="))
        self.label_3.setText(_translate("MainWindow", "X1S ="))
        self.label_1.setText(_translate("MainWindow", "Uср.НН = "))
        self.label_5.setText(_translate("MainWindow", "В"))
        self.label_6.setText(_translate("MainWindow", "Ом"))
        self.label_7.setText(_translate("MainWindow", "Ом"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Трансформатор"))
        self.label_9.setText(_translate("MainWindow", "lк ="))
        self.label_10.setText(_translate("MainWindow", "м"))
        self.label_11.setText(_translate("MainWindow", "длина линии"))
        self.label_12.setText(_translate("MainWindow", "сечение кабеля"))
        self.label_13.setText(_translate("MainWindow", "мм2"))
        self.label_14.setText(_translate("MainWindow", "Sк ="))
        self.label_15.setText(_translate("MainWindow", "материал жилы кабеля"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Медь"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Алюминий"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Линия"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Сопротивление прочих элементов цепи"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Аппарат защиты"))
        self.label_4.setText(_translate("MainWindow", "Iп0(1) ="))
        self.label_8.setText(_translate("MainWindow", "кА"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Результаты"))
        self.menu_File.setTitle(_translate("MainWindow", "&Файл"))
        self.menu_Calculation.setTitle(_translate("MainWindow", "Расчёт"))
        self.menu_Report.setTitle(_translate("MainWindow", "Отчёт"))
        self.menu_Help.setTitle(_translate("MainWindow", "Справка"))
        self.action_Calculate.setText(_translate("MainWindow", "Запустить расчёт"))
        self.action_About.setText(_translate("MainWindow", "О программе..."))
        self.action_Open.setText(_translate("MainWindow", "Открыть"))
        self.action_Save.setText(_translate("MainWindow", "Сохранить"))
        self.action_Exit.setText(_translate("MainWindow", "В&ыход"))

