# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(710, 330, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 781, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lineEdit_R_1sum = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_R_1sum.setGeometry(QtCore.QRect(70, 40, 113, 20))
        self.lineEdit_R_1sum.setObjectName("lineEdit_R_1sum")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_U_sr_NN = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_U_sr_NN.setGeometry(QtCore.QRect(70, 10, 113, 20))
        self.lineEdit_U_sr_NN.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_U_sr_NN.setObjectName("lineEdit_U_sr_NN")
        self.label_1 = QtWidgets.QLabel(self.tab)
        self.label_1.setGeometry(QtCore.QRect(10, 10, 51, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.lineEdit_X_1sum = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_X_1sum.setGeometry(QtCore.QRect(70, 70, 113, 20))
        self.lineEdit_X_1sum.setObjectName("lineEdit_X_1sum")
        self.lineEdit_Ip01 = QtWidgets.QLineEdit(self.tab)
        self.lineEdit_Ip01.setGeometry(QtCore.QRect(70, 100, 113, 20))
        self.lineEdit_Ip01.setObjectName("lineEdit_Ip01")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(10, 100, 41, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(190, 10, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(190, 40, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(190, 70, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(190, 100, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_Calculation = QtWidgets.QMenu(self.menubar)
        self.menu_Calculation.setObjectName("menu_Calculation")
        self.menu_Report = QtWidgets.QMenu(self.menubar)
        self.menu_Report.setObjectName("menu_Report")
        self.menu_Help = QtWidgets.QMenu(self.menubar)
        self.menu_Help.setObjectName("menu_Help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_Calculate = QtWidgets.QAction(MainWindow)
        self.action_Calculate.setObjectName("action_Calculate")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Open = QtWidgets.QAction(MainWindow)
        self.action_Open.setObjectName("action_Open")
        self.action_Save = QtWidgets.QAction(MainWindow)
        self.action_Save.setObjectName("action_Save")
        self.action_Exit = QtWidgets.QAction(MainWindow)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_Open)
        self.menu_File.addAction(self.action_Save)
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.action_Exit)
        self.menu_Calculation.addAction(self.action_Calculate)
        self.menu_Help.addAction(self.action_About)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Calculation.menuAction())
        self.menubar.addAction(self.menu_Report.menuAction())
        self.menubar.addAction(self.menu_Help.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.lineEdit_U_sr_NN)
        MainWindow.setTabOrder(self.lineEdit_U_sr_NN, self.lineEdit_R_1sum)
        MainWindow.setTabOrder(self.lineEdit_R_1sum, self.lineEdit_X_1sum)
        MainWindow.setTabOrder(self.lineEdit_X_1sum, self.lineEdit_Ip01)
        MainWindow.setTabOrder(self.lineEdit_Ip01, self.pushButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "R1S ="))
        self.label_3.setText(_translate("MainWindow", "X1S ="))
        self.label_1.setText(_translate("MainWindow", "Uср.НН = "))
        self.label_4.setText(_translate("MainWindow", "Iп0(1) ="))
        self.label_5.setText(_translate("MainWindow", "В"))
        self.label_6.setText(_translate("MainWindow", "Ом"))
        self.label_7.setText(_translate("MainWindow", "Ом"))
        self.label_8.setText(_translate("MainWindow", "кА"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.menu_File.setTitle(_translate("MainWindow", "&Файл"))
        self.menu_Calculation.setTitle(_translate("MainWindow", "Расчёт"))
        self.menu_Report.setTitle(_translate("MainWindow", "Отчёт"))
        self.menu_Help.setTitle(_translate("MainWindow", "Справка"))
        self.action_Calculate.setText(_translate("MainWindow", "Запустить расчёт"))
        self.action_About.setText(_translate("MainWindow", "О программе..."))
        self.action_Open.setText(_translate("MainWindow", "Открыть"))
        self.action_Save.setText(_translate("MainWindow", "Сохранить"))
        self.action_Exit.setText(_translate("MainWindow", "В&ыход"))

